//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1135 with alias "footerContent"
	/// <summary>_FooterContent</summary>
	public partial interface IFooterContent : IPublishedContent
	{
		/// <summary>#prop.FooterContentOne</summary>
		IHtmlString FooterContentOne { get; }

		/// <summary>#prop.FooterContentThree</summary>
		IHtmlString FooterContentThree { get; }

		/// <summary>#prop.FooterContentTwo</summary>
		IHtmlString FooterContentTwo { get; }
	}

	/// <summary>_FooterContent</summary>
	[PublishedContentModel("footerContent")]
	public partial class FooterContent : PublishedContentModel, IFooterContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "footerContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FooterContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FooterContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #prop.FooterContentOne: #prop.FooterContentOne.d
		///</summary>
		[ImplementPropertyType("footerContentOne")]
		public IHtmlString FooterContentOne
		{
			get { return GetFooterContentOne(this); }
		}

		/// <summary>Static getter for #prop.FooterContentOne</summary>
		public static IHtmlString GetFooterContentOne(IFooterContent that) { return that.GetPropertyValue<IHtmlString>("footerContentOne"); }

		///<summary>
		/// #prop.FooterContentThree: #prop.FooterContentThree.d
		///</summary>
		[ImplementPropertyType("footerContentThree")]
		public IHtmlString FooterContentThree
		{
			get { return GetFooterContentThree(this); }
		}

		/// <summary>Static getter for #prop.FooterContentThree</summary>
		public static IHtmlString GetFooterContentThree(IFooterContent that) { return that.GetPropertyValue<IHtmlString>("footerContentThree"); }

		///<summary>
		/// #prop.FooterContentTwo: #prop.FooterContentTwo.d
		///</summary>
		[ImplementPropertyType("footerContentTwo")]
		public IHtmlString FooterContentTwo
		{
			get { return GetFooterContentTwo(this); }
		}

		/// <summary>Static getter for #prop.FooterContentTwo</summary>
		public static IHtmlString GetFooterContentTwo(IFooterContent that) { return that.GetPropertyValue<IHtmlString>("footerContentTwo"); }
	}
}
