//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1135 with alias "footerContent"
	/// <summary>_FooterContent</summary>
	public partial interface IFooterContent : IPublishedContent
	{
		/// <summary>#prop.FooterContentItems</summary>
		IEnumerable<IPublishedContent> FooterContentItems { get; }
	}

	/// <summary>_FooterContent</summary>
	[PublishedContentModel("footerContent")]
	public partial class FooterContent : PublishedContentModel, IFooterContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "footerContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FooterContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FooterContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #prop.FooterContentItems: #prop.FooterContentItems.d
		///</summary>
		[ImplementPropertyType("footerContentItems")]
		public IEnumerable<IPublishedContent> FooterContentItems
		{
			get { return GetFooterContentItems(this); }
		}

		/// <summary>Static getter for #prop.FooterContentItems</summary>
		public static IEnumerable<IPublishedContent> GetFooterContentItems(IFooterContent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("footerContentItems"); }
	}
}
