//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>_FooterItem</summary>
	[PublishedContentModel("footerItem")]
	public partial class FooterItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "footerItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FooterItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FooterItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #prop.FooterItem.Headline: #prop.FooterItem.Headline.d
		///</summary>
		[ImplementPropertyType("footerItemHeadline")]
		public string FooterItemHeadline
		{
			get { return this.GetPropertyValue<string>("footerItemHeadline"); }
		}

		///<summary>
		/// #prop.FooterItem.LinkList: #prop.FooterItem.LinkList.d
		///</summary>
		[ImplementPropertyType("footerItemLinkList")]
		public IEnumerable<RJP.MultiUrlPicker.Models.Link> FooterItemLinkList
		{
			get { return this.GetPropertyValue<IEnumerable<RJP.MultiUrlPicker.Models.Link>>("footerItemLinkList"); }
		}

		///<summary>
		/// #prop.FooterItem.Text: #prop.FooterItem.Text.d
		///</summary>
		[ImplementPropertyType("footerItemText")]
		public IHtmlString FooterItemText
		{
			get { return this.GetPropertyValue<IHtmlString>("footerItemText"); }
		}
	}
}
