//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>#doctype.GalleryPage</summary>
	[PublishedContentModel("galleryPage")]
	public partial class GalleryPage : PublishedContentModel, IImageGallery
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "galleryPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GalleryPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GalleryPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #prop.imageGallery.GridColumns: #prop.ImageGallery.GridColumns.d
		///</summary>
		[ImplementPropertyType("imageGalleryGridColumns")]
		public decimal ImageGalleryGridColumns
		{
			get { return Umbraco.Web.PublishedContentModels.ImageGallery.GetImageGalleryGridColumns(this); }
		}

		///<summary>
		/// #prop.ImageGallery.Heading: #prop.ImageGallery.Heading.d
		///</summary>
		[ImplementPropertyType("imageGalleryHeading")]
		public string ImageGalleryHeading
		{
			get { return Umbraco.Web.PublishedContentModels.ImageGallery.GetImageGalleryHeading(this); }
		}

		///<summary>
		/// #prop.ImageGallery.Images: #prop.ImageGallery.Images.d
		///</summary>
		[ImplementPropertyType("imageGalleryImages")]
		public IEnumerable<IPublishedContent> ImageGalleryImages
		{
			get { return Umbraco.Web.PublishedContentModels.ImageGallery.GetImageGalleryImages(this); }
		}

		///<summary>
		/// #prop.ImageGallery.ShowAsGrid: #prop.ImageGallery.ShowAsGrid.d
		///</summary>
		[ImplementPropertyType("imageGalleryShowAsGrid")]
		public bool ImageGalleryShowAsGrid
		{
			get { return Umbraco.Web.PublishedContentModels.ImageGallery.GetImageGalleryShowAsGrid(this); }
		}

		///<summary>
		/// #prop.ImageGallery.ShowInfo: #prop.ImageGallery.ShowInfo.d
		///</summary>
		[ImplementPropertyType("imageGalleryShowInfo")]
		public bool ImageGalleryShowInfo
		{
			get { return Umbraco.Web.PublishedContentModels.ImageGallery.GetImageGalleryShowInfo(this); }
		}
	}
}
