//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>#doctype.HomePage</summary>
	[PublishedContentModel("homePage")]
	public partial class HomePage : PublishedContentModel, IFooterContent, IPageContent, ISEometaData, ISiteSettings
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #prop.FocusArticlesList: #prop.FocusArticlesList.d
		///</summary>
		[ImplementPropertyType("focusArticles")]
		public IEnumerable<IPublishedContent> FocusArticles
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("focusArticles"); }
		}

		///<summary>
		/// #prop.FocusArticlesHeadline: #prop.FocusArticlesHeadline.d
		///</summary>
		[ImplementPropertyType("focusArticlesHeadline")]
		public string FocusArticlesHeadline
		{
			get { return this.GetPropertyValue<string>("focusArticlesHeadline"); }
		}

		///<summary>
		/// #prop.FooterContentOne: #prop.FooterContentOne.d
		///</summary>
		[ImplementPropertyType("footerContentOne")]
		public IHtmlString FooterContentOne
		{
			get { return Umbraco.Web.PublishedContentModels.FooterContent.GetFooterContentOne(this); }
		}

		///<summary>
		/// #prop.FooterContentThree: #prop.FooterContentThree.d
		///</summary>
		[ImplementPropertyType("footerContentThree")]
		public IHtmlString FooterContentThree
		{
			get { return Umbraco.Web.PublishedContentModels.FooterContent.GetFooterContentThree(this); }
		}

		///<summary>
		/// #prop.FooterContentTwo: #prop.FooterContentTwo.d
		///</summary>
		[ImplementPropertyType("footerContentTwo")]
		public IHtmlString FooterContentTwo
		{
			get { return Umbraco.Web.PublishedContentModels.FooterContent.GetFooterContentTwo(this); }
		}

		///<summary>
		/// #prop.PageBodyText: #prop.PageBodyText.d
		///</summary>
		[ImplementPropertyType("bodyText")]
		public IHtmlString BodyText
		{
			get { return Umbraco.Web.PublishedContentModels.PageContent.GetBodyText(this); }
		}

		///<summary>
		/// #prop.PageHeadline: #prop.PageHeadline.d
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return Umbraco.Web.PublishedContentModels.PageContent.GetHeadline(this); }
		}

		///<summary>
		/// #prop.PageLead: #prop.PageLead.d
		///</summary>
		[ImplementPropertyType("lead")]
		public IHtmlString Lead
		{
			get { return Umbraco.Web.PublishedContentModels.PageContent.GetLead(this); }
		}

		///<summary>
		/// #prop.MainImage: #prop.MainImage.d
		///</summary>
		[ImplementPropertyType("mainImage")]
		public IPublishedContent MainImage
		{
			get { return Umbraco.Web.PublishedContentModels.PageContent.GetMainImage(this); }
		}

		///<summary>
		/// #prop.SEO.MetaData.Keywords: #prop.SEO.MetaData.Keywords.d
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public IEnumerable<string> SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.SEometaData.GetSeoKeywords(this); }
		}

		///<summary>
		/// #prop.SEO.MetaData.Description: #prop.SEO.MetaData.Description.d
		///</summary>
		[ImplementPropertyType("seoMetaDescription")]
		public string SeoMetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.SEometaData.GetSeoMetaDescription(this); }
		}

		///<summary>
		/// #prop.SiteSettings.DeactivateLogoLink: #prop.SiteSettings.DeactivateLogoLink.d
		///</summary>
		[ImplementPropertyType("deactivateLogoLink")]
		public bool DeactivateLogoLink
		{
			get { return Umbraco.Web.PublishedContentModels.SiteSettings.GetDeactivateLogoLink(this); }
		}

		///<summary>
		/// #prop.SiteSettings.HideHomePageInNavigation: #prop.SiteSettings.HideHomePageInNavigation.d
		///</summary>
		[ImplementPropertyType("hideHomePageInNavigation")]
		public bool HideHomePageInNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.SiteSettings.GetHideHomePageInNavigation(this); }
		}

		///<summary>
		/// #prop.SiteSettings.MainNavigation: #prop.SiteSettings.MainNavigation.d
		///</summary>
		[ImplementPropertyType("mainNavigation")]
		public IEnumerable<IPublishedContent> MainNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.SiteSettings.GetMainNavigation(this); }
		}

		///<summary>
		/// #prop.SiteSettings.ServiceNavigation: #prop.SiteSettings.ServiceNavigation.d
		///</summary>
		[ImplementPropertyType("serviceNavigation")]
		public IEnumerable<RJP.MultiUrlPicker.Models.Link> ServiceNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.SiteSettings.GetServiceNavigation(this); }
		}

		///<summary>
		/// #prop.SiteSettings.Logo: #prop.SiteSettings.Logo.d
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public IPublishedContent SiteLogo
		{
			get { return Umbraco.Web.PublishedContentModels.SiteSettings.GetSiteLogo(this); }
		}

		///<summary>
		/// #prop.SiteSettings.Logo.Neg: #prop.SiteSettings.Logo.Neg.d
		///</summary>
		[ImplementPropertyType("siteLogoNegative")]
		public IPublishedContent SiteLogoNegative
		{
			get { return Umbraco.Web.PublishedContentModels.SiteSettings.GetSiteLogoNegative(this); }
		}

		///<summary>
		/// #prop.SiteSettings.SiteName: #prop.SiteSettings.SiteName.d
		///</summary>
		[ImplementPropertyType("siteName")]
		public string SiteName
		{
			get { return Umbraco.Web.PublishedContentModels.SiteSettings.GetSiteName(this); }
		}
	}
}
