//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1154 with alias "imageGallery"
	/// <summary>_ImageGallery</summary>
	public partial interface IImageGallery : IPublishedContent
	{
		/// <summary>#prop.imageGallery.GridColumns</summary>
		decimal ImageGalleryGridColumns { get; }

		/// <summary>#prop.ImageGallery.Heading</summary>
		string ImageGalleryHeading { get; }

		/// <summary>#prop.ImageGallery.Images</summary>
		IEnumerable<IPublishedContent> ImageGalleryImages { get; }

		/// <summary>#prop.ImageGallery.ShowAsGrid</summary>
		bool ImageGalleryShowAsGrid { get; }

		/// <summary>#prop.ImageGallery.ShowInfo</summary>
		bool ImageGalleryShowInfo { get; }
	}

	/// <summary>_ImageGallery</summary>
	[PublishedContentModel("imageGallery")]
	public partial class ImageGallery : PublishedContentModel, IImageGallery
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "imageGallery";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ImageGallery(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageGallery, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #prop.imageGallery.GridColumns: #prop.ImageGallery.GridColumns.d
		///</summary>
		[ImplementPropertyType("imageGalleryGridColumns")]
		public decimal ImageGalleryGridColumns
		{
			get { return GetImageGalleryGridColumns(this); }
		}

		/// <summary>Static getter for #prop.imageGallery.GridColumns</summary>
		public static decimal GetImageGalleryGridColumns(IImageGallery that) { return that.GetPropertyValue<decimal>("imageGalleryGridColumns"); }

		///<summary>
		/// #prop.ImageGallery.Heading: #prop.ImageGallery.Heading.d
		///</summary>
		[ImplementPropertyType("imageGalleryHeading")]
		public string ImageGalleryHeading
		{
			get { return GetImageGalleryHeading(this); }
		}

		/// <summary>Static getter for #prop.ImageGallery.Heading</summary>
		public static string GetImageGalleryHeading(IImageGallery that) { return that.GetPropertyValue<string>("imageGalleryHeading"); }

		///<summary>
		/// #prop.ImageGallery.Images: #prop.ImageGallery.Images.d
		///</summary>
		[ImplementPropertyType("imageGalleryImages")]
		public IEnumerable<IPublishedContent> ImageGalleryImages
		{
			get { return GetImageGalleryImages(this); }
		}

		/// <summary>Static getter for #prop.ImageGallery.Images</summary>
		public static IEnumerable<IPublishedContent> GetImageGalleryImages(IImageGallery that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("imageGalleryImages"); }

		///<summary>
		/// #prop.ImageGallery.ShowAsGrid: #prop.ImageGallery.ShowAsGrid.d
		///</summary>
		[ImplementPropertyType("imageGalleryShowAsGrid")]
		public bool ImageGalleryShowAsGrid
		{
			get { return GetImageGalleryShowAsGrid(this); }
		}

		/// <summary>Static getter for #prop.ImageGallery.ShowAsGrid</summary>
		public static bool GetImageGalleryShowAsGrid(IImageGallery that) { return that.GetPropertyValue<bool>("imageGalleryShowAsGrid"); }

		///<summary>
		/// #prop.ImageGallery.ShowInfo: #prop.ImageGallery.ShowInfo.d
		///</summary>
		[ImplementPropertyType("imageGalleryShowInfo")]
		public bool ImageGalleryShowInfo
		{
			get { return GetImageGalleryShowInfo(this); }
		}

		/// <summary>Static getter for #prop.ImageGallery.ShowInfo</summary>
		public static bool GetImageGalleryShowInfo(IImageGallery that) { return that.GetPropertyValue<bool>("imageGalleryShowInfo"); }
	}
}
