//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1090 with alias "sEOMetaData"
	/// <summary>_SEO.MetaData</summary>
	public partial interface ISEometaData : IPublishedContent
	{
		/// <summary>#prop.SEO.MetaData.Keywords</summary>
		IEnumerable<string> SeoKeywords { get; }

		/// <summary>#prop.SEO.MetaData.Description</summary>
		string SeoMetaDescription { get; }
	}

	/// <summary>_SEO.MetaData</summary>
	[PublishedContentModel("sEOMetaData")]
	public partial class SEometaData : PublishedContentModel, ISEometaData
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sEOMetaData";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SEometaData(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SEometaData, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #prop.SEO.MetaData.Keywords: #prop.SEO.MetaData.Keywords.d
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public IEnumerable<string> SeoKeywords
		{
			get { return GetSeoKeywords(this); }
		}

		/// <summary>Static getter for #prop.SEO.MetaData.Keywords</summary>
		public static IEnumerable<string> GetSeoKeywords(ISEometaData that) { return that.GetPropertyValue<IEnumerable<string>>("seoKeywords"); }

		///<summary>
		/// #prop.SEO.MetaData.Description: #prop.SEO.MetaData.Description.d
		///</summary>
		[ImplementPropertyType("seoMetaDescription")]
		public string SeoMetaDescription
		{
			get { return GetSeoMetaDescription(this); }
		}

		/// <summary>Static getter for #prop.SEO.MetaData.Description</summary>
		public static string GetSeoMetaDescription(ISEometaData that) { return that.GetPropertyValue<string>("seoMetaDescription"); }
	}
}
